version: "3"
networks:
  expense:
volumes:
  mysql: #docker volume create mysql
services:
  mysql:
    image: pmahalakshmi25/mysql:v1
    container_name: mysql #like --name mysql
    volumes:
    - mysql:/var/lib/mysql #-v mysql:/var/lib/mysql
  backend:
    image: pmahalakshmi25/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: pmahalakshmi25/frontend:v1
    container_name: frontend
    ports:
      - "80:80" #-p 80:80
    depends_on:
      - backend
